// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActiveWebapp = { id: string; name: string | null };

export type AncsAuthStatus = 'unknown' | 'probing' | 'authorized' | 'unauthorized';

export type AncsAuthStatusEntry = { deviceId: string; status: AncsAuthStatus };

export type ArtifactDigest = { size: number; sha256: string };

export type AuthKind = 'idle' | 'pending' | 'authenticated' | 'failed';

export type AuthState = {
  kind: AuthKind;
  userCode: string | null;
  verificationUrl: string | null;
  verificationUrlComplete: string | null;
  message: string | null;
};

export type CapabilityFlags = {
  geo: boolean;
  notifications: boolean;
  netFetch: boolean;
  netWs: boolean;
  audioTts: boolean;
  voiceModel: boolean;
};

export type CompanionConfig = {
  host: HostInfo;
  capabilities: CapabilityFlags;
  stateDir: string;
  cacheDir: string;
  modelPlatform: ModelPlatform | null;
  spotify: SpotifyProviderConfig | null;
};

export type CompanionDebug = {
  authorityPlaybackHeld: boolean;
  authorityMetadataHeld: boolean;
  authorityVolumeHeld: boolean;
  authorityAppBundle: string | null;
  arbitratedSource: string | null;
  librarySource: string | null;
  lastPlayedFrom: string | null;
  attachedProviders: Array<string>;
  attachedSchemes: Array<string>;
  linkedDevices: Array<string>;
  autoResume: Array<DeviceAutoResume>;
  resumeTargets: Array<DeviceResumeTarget>;
  voice: VoiceDebug;
};

export type ConfigEntry = { key: string; value: string };

export type ConfigField = {
  kind: ConfigKind;
  key: string;
  label: string;
  pattern: string | null;
  minLength: number | null;
  maxLength: number | null;
  min: number | null;
  max: number | null;
  step: number | null;
  choices: Array<string>;
  defaultValue: string | null;
};

export type ConfigKind = 'string' | 'number' | 'boolean' | 'enum' | 'secret';

export type DeviceAutoResume = { deviceId: string; enabled: boolean };

export type DeviceLogLine = {
  seq: number;
  tsUnixMs: number;
  origin: LogOrigin;
  level: LogLevel;
  target: string;
  message: string;
};

export type DeviceMeta = {
  daemonVersion: string;
  libbridgethingVersion: string;
  imageVersion: string;
  appName: string;
  osName: string;
  osVersion: string;
  channel: string;
  modelName: string;
  serialNumber: string;
  nickname: string | null;
};

export type DeviceMetaEntry = { deviceId: string; meta: DeviceMeta };

export type DeviceResumeTarget = { deviceId: string; target: ResumeTarget };

export type DeviceWebappsEntry = {
  deviceId: string;
  webapps: Array<WebappInfo>;
  active: ActiveWebapp | null;
  listed: boolean;
};

export type DocEntry = { key: string; value: string };

export type ExtensionInfo = { permissions: Array<string>; api: number };

export type HostInfo = {
  appName: string;
  appVersion: string;
  osName: string;
  osVersion: string;
  hostIdentifier: string;
};

export type LogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error';

export type LogOrigin = 'device' | 'host';

export type LrcLine = { startMs: number; text: string };

export type ModelPlatform = 'ios' | 'android' | 'macos' | 'linux' | 'windows';

export type NluFastPathAmount = 'small' | 'medium' | 'large';

export type NluFastPathDirection = 'up' | 'down';

export type NluFastPathHit = { intent: string; slots: NluFastPathSlots };

export type NluFastPathRepeatMode = 'off' | 'all' | 'one';

export type NluFastPathSlots = {
  preset: string | null;
  level: number | null;
  speed: NluFastPathSpeed | null;
  seconds: number | null;
  repeatMode: NluFastPathRepeatMode | null;
  enabled: boolean | null;
  view: NluFastPathView | null;
  mute: boolean | null;
  direction: NluFastPathDirection | null;
  amount: NluFastPathAmount | null;
};

export type NluFastPathSpeed = 'one' | 'onePointTwo' | 'onePointFive' | 'two';

export type NluFastPathView =
  | 'nowPlaying'
  | 'artist'
  | 'album'
  | 'playlist'
  | 'playlists'
  | 'library'
  | 'songs'
  | 'presets'
  | 'queue'
  | 'savedEpisodes'
  | 'newEpisodes';

export type NluIntentCatalog = { surfaceNames: Array<string>; noIntent: string; clarify: string };

export type NluRejectionOutcome =
  | { accept: { intent: string } }
  | 'noIntent'
  | { clarify: { alternates: Array<string> } };

export type NluRejectionPolicy = { inDomainThreshold: number; clarifyMargin: number; maxAlternates: number };

export type NowPlaying = { track: NowPlayingTrack | null; playback: NowPlayingPlayback; appName: string | null };

export type NowPlayingPlayback = { playing: boolean; positionMs: number; shuffle: boolean; repeatMode: RepeatMode };

export type NowPlayingTrack = {
  id: string | null;
  title: string | null;
  artist: string | null;
  album: string | null;
  artworkUrl: string | null;
  durationMs: number | null;
};

export type OtaApplyPhase = 'streaming' | 'verifying' | 'writing' | 'confirming' | 'reboot';

export type OtaArtifactUrls = {
  daemonBinary: string;
  daemonBinaryZst: string;
  imageSwu: string;
  imageZck: string;
  imageBootZck: string;
};

export type OtaAvailable = {
  deviceId: string;
  releaseVersion: string | null;
  daemonVersion: string | null;
  imageVersion: string | null;
};

export type OtaCompositeVersion = { daemon: string; image: string };

export type OtaDiscoverManifest = {
  manifestVersion: number;
  updatedAt: string;
  channels: { [key in string]: OtaManifestChannel };
  releases: { [key in string]: OtaManifestRelease };
};

export type OtaKind = 'image' | 'daemon' | 'builtinWebapp' | 'installedWebapp' | 'wakewordModel';

export type OtaManifestChannel = {
  name: string;
  stability: string;
  isDefault: boolean;
  latest: string;
  releases: Array<string>;
};

export type OtaManifestRelease = {
  version: string;
  channel: string;
  yanked: string | null;
  deprecated: boolean;
  builtinWebapps: { [key in string]: string };
  artifacts: OtaReleaseArtifacts | null;
};

export type OtaPatchDigest = { size: number; sha256: string; sourceSha256: string | null };

export type OtaPhaseSnapshot =
  | 'idle'
  | { downloading: { asset: string; received: number; total: number; ratePerSec: number | null } }
  | { streaming: { asset: string; sent: number; total: number; ratePerSec: number | null; etaSeconds: number | null } }
  | { applying: { phase: OtaApplyPhase; writePercent: number; dwlPercent: number; dwlBytes: number } }
  | 'staged'
  | 'completed'
  | { failed: { reason: string } };

export type OtaPlanStep = { id: number; kind: OtaStepKind; label: string; bytes: number };

export type OtaPollConfig = { intervalSeconds: number; autoPush: boolean; rootUrl: string | null };

export type OtaPollEvent =
  | { manifestPolled: { updatedAt: string } }
  | { manifestPollFailed: { reason: string } }
  | { updateAvailable: { deviceId: string; release: string; daemonVersion: string; imageVersion: string } }
  | {
      planned: {
        deviceId: string;
        kind: OtaKind;
        release: string;
        daemonVersion: string;
        imageVersion: string;
        channel: string;
        rootUrl: string;
        steps: Array<OtaPlanStep>;
      };
    }
  | { progress: { deviceId: string; kind: OtaKind; stepId: number; snapshot: OtaPhaseSnapshot } }
  | { updated: { deviceId: string; kind: OtaKind; version: string } }
  | { failed: { deviceId: string; kind: OtaKind; reason: string } };

export type OtaPollStatus = { lastPolledAt: string | null; error: string | null };

export type OtaReleaseArtifacts = {
  daemon: ArtifactDigest | null;
  daemonZst: ArtifactDigest | null;
  imageSwu: ArtifactDigest | null;
  imageZck: ArtifactDigest | null;
  imageBootZck: ArtifactDigest | null;
  webapps: { [key in string]: ArtifactDigest };
  daemonPatches: { [key in string]: OtaPatchDigest };
};

export type OtaRun = {
  runId: string;
  deviceId: string;
  kind: OtaKind;
  phase: OtaRunPhase;
  steps: Array<OtaPlanStep>;
  stepId: number;
  startedAtMs: number;
  phaseStartedAtMs: number;
  stageReceived: number | null;
  stageTotal: number | null;
  ratePerSec: number | null;
  dwlPercent: number | null;
  outcome: OtaRunOutcome | null;
  error: string | null;
  releaseVersion: string | null;
  daemonVersion: string | null;
  imageVersion: string | null;
  channel: string | null;
  rootUrl: string | null;
  resumable: boolean;
  webappId: string | null;
  webappName: string | null;
};

export type OtaRunOutcome = 'succeeded' | 'failed' | 'cancelled';

export type OtaRunPhase =
  | 'idle'
  | 'downloading'
  | 'streaming'
  | 'verifying'
  | 'writing'
  | 'confirming'
  | 'reboot'
  | 'completed'
  | 'failed';

export type OtaRunProgress = {
  percent: number;
  stepIndex: number;
  stepCount: number;
  stepLabel: string | null;
  etaSeconds: number | null;
};

export type OtaStepKind = 'download' | 'stream' | 'apply' | 'reboot';

export type OtaStoreChange =
  | { run: { run: OtaRun } }
  | { available: { available: OtaAvailable } }
  | { poll: { status: OtaPollStatus } };

export type PeerLinkStatus = 'connected' | 'linkFailed';

export type ProviderCredentials =
  | { kind: 'oauthTokens'; accessToken: string; refreshToken: string }
  | { kind: 'serverLogin'; serverUrl: string; username: string; password: string };

export type ProviderInfo = {
  id: string;
  displayName: string;
  available: boolean;
  connected: boolean;
  signIn: SignInMethod;
  authState: AuthState;
  serviceHealth: ServiceHealth;
};

export type RepeatMode = 'off' | 'one' | 'all';

export type ResumeTarget = 'phoneOnly' | 'anySpeaker';

export type ServiceHealth = { kind: ServiceHealthKind; retryAfterSeconds: number | null };

export type ServiceHealthKind = 'ok' | 'rateLimited' | 'unreachable';

export type SessionEvent =
  | { providersChanged: { providers: Array<ProviderInfo> } }
  | { peerConnected: { peer: SessionPeer } }
  | { peerDisconnected: { deviceId: string } }
  | { peerLinkFailed: { peer: SessionPeer } }
  | { nowPlayingChanged: { nowPlaying: NowPlaying | null } }
  | { ancsAuthStatusChanged: { deviceId: string; status: AncsAuthStatus } }
  | { log: { origin: LogOrigin; level: LogLevel; target: string; message: string } }
  | { webappsChanged: { entry: DeviceWebappsEntry } }
  | { webappDocChanged: { deviceId: string; webappId: string; key: string; value: string | null } }
  | { deviceMetaChanged: { deviceId: string; meta: DeviceMeta } }
  | { voiceModelStateChanged: { state: VoiceModelState } }
  | { voiceTurnChanged: { turn: VoiceTurn } }
  | { otaRunChanged: { run: OtaRun } }
  | { otaAvailableChanged: { available: OtaAvailable } }
  | { otaPollChanged: { status: OtaPollStatus } }
  | { companionUpdateProgress: { received: number; total: number } }
  | 'resumed';

export type SessionHostInfo = {
  appName: string;
  appVersion: string;
  osName: string;
  osVersion: string;
  hostIdentifier: string;
  libVersion: string;
  libbridgethingVersion: string;
  adapterVersion: string;
};

export type SessionPeer = { id: string; name: string; status: PeerLinkStatus; linkError: string | null };

export type SessionSnapshot = {
  hostInfo: SessionHostInfo;
  providers: Array<ProviderInfo>;
  providerPriority: Array<string>;
  libraryProvider: string | null;
  peers: Array<SessionPeer>;
  ancsAuthStatuses: Array<AncsAuthStatusEntry>;
  nowPlaying: NowPlaying | null;
  deviceMeta: Array<DeviceMetaEntry>;
  capabilityFlags: CapabilityFlags;
  voiceModel: VoiceModelState;
  otaPollConfig: OtaPollConfig | null;
  webapps: Array<DeviceWebappsEntry>;
  otaRuns: Array<OtaRun>;
  otaAvailable: Array<OtaAvailable>;
  otaPoll: OtaPollStatus;
};

export type SignInMethod = 'handshake' | 'serverLogin';

export type SpotifyProviderConfig = { workerBase: string; psk: string };

export type VoiceDebug = {
  hasModel: boolean;
  armedBundle: string | null;
  transferAllowed: boolean;
  paths: VoiceModelPaths;
};

export type VoiceModelPaths = { nluBundleDir: string | null; asrWeights: string | null };

export type VoiceModelState = {
  status: VoiceModelStatus;
  receivedBytes: number;
  totalBytes: number;
  version: string | null;
  error: string | null;
};

export type VoiceModelStatus = 'absent' | 'downloading' | 'ready' | 'failed';

export type VoiceTurn = {
  deviceId: string;
  streamId: string;
  trigger: VoiceTurnTrigger;
  phase: VoiceTurnPhase;
  transcript: string | null;
  intent: string | null;
};

export type VoiceTurnPhase = 'listening' | 'resolved' | 'cancelled';

export type VoiceTurnTrigger = 'pushToTalk' | 'assistant' | 'wakeWord';

export type WebappInfo = {
  id: string;
  name: string;
  source: WebappSource;
  role: WebappRole;
  version: string;
  provenance: string | null;
  description: string | null;
  iconHash: string | null;
  settingsHash: string | null;
  overlayHash: string | null;
  config: Array<ConfigField>;
  permissions: Array<string>;
  extension: ExtensionInfo | null;
};

export type WebappResourceFile = { path: string; mime: string | null };

export type WebappResourceKind = 'icon' | 'settings' | 'overlay';

export type WebappResourceOrigin = { url: string; sha256: string; size: number; mime: string | null };

export type WebappRole = 'standard' | 'launcher';

export type WebappSlot = 'launcher' | 'overlay';

export type WebappSlots = { launcher: string | null; overlay: string | null };

export type WebappSource = 'builtin' | 'installed';
