#[path = "../../../../../src/backends/windows/connectivity.rs"]
pub mod connectivity;
#[path = "../../../../../src/backends/windows/geo.rs"]
pub mod geo;
#[path = "../../../../../src/backends/windows/media.rs"]
pub mod media;
#[path = "../../../../../src/backends/windows/speech.rs"]
pub mod speech;
#[path = "../../../../../src/backends/windows/stream.rs"]
pub mod stream;
#[path = "../../../../../src/backends/windows/volume.rs"]
pub mod volume;
