// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.
// Re-generate with `just codegen` (or `just rust`).

use crate::Client;
use bridgething_sdk_runtime::{RequestFailure, SdkError};
use futures::{Stream, StreamExt, future::ready};
use libbridgething::{client::*, *};
use tokio_stream::wrappers::BroadcastStream;

impl Client {
  /// The `Asset` surface.
  pub fn asset(&self) -> AssetSurface<'_> {
    AssetSurface(self)
  }
  /// The `Audio` surface.
  pub fn audio(&self) -> AudioSurface<'_> {
    AudioSurface(self)
  }
  /// The `Bluetooth` surface.
  pub fn bluetooth(&self) -> BluetoothSurface<'_> {
    BluetoothSurface(self)
  }
  /// The `Capabilities` surface.
  pub fn capabilities(&self) -> CapabilitiesSurface<'_> {
    CapabilitiesSurface(self)
  }
  /// The `Config` surface.
  pub fn config(&self) -> ConfigSurface<'_> {
    ConfigSurface(self)
  }
  /// The `Doc` surface.
  pub fn doc(&self) -> DocSurface<'_> {
    DocSurface(self)
  }
  /// The `Geo` surface.
  pub fn geo(&self) -> GeoSurface<'_> {
    GeoSurface(self)
  }
  /// The `Hardware` surface.
  pub fn hardware(&self) -> HardwareSurface<'_> {
    HardwareSurface(self)
  }
  /// The `Library` surface.
  pub fn library(&self) -> LibrarySurface<'_> {
    LibrarySurface(self)
  }
  /// The `Net` surface.
  pub fn net(&self) -> NetSurface<'_> {
    NetSurface(self)
  }
  /// The `Notifications` surface.
  pub fn notifications(&self) -> NotificationsSurface<'_> {
    NotificationsSurface(self)
  }
  /// The `Peer` surface.
  pub fn peer(&self) -> PeerSurface<'_> {
    PeerSurface(self)
  }
  /// The `Phone` surface.
  pub fn phone(&self) -> PhoneSurface<'_> {
    PhoneSurface(self)
  }
  /// The `Player` surface.
  pub fn player(&self) -> PlayerSurface<'_> {
    PlayerSurface(self)
  }
  /// The `System` surface.
  pub fn system(&self) -> SystemSurface<'_> {
    SystemSurface(self)
  }
  /// The `Time` surface.
  pub fn time(&self) -> TimeSurface<'_> {
    TimeSurface(self)
  }
  /// The `Voice` surface.
  pub fn voice(&self) -> VoiceSurface<'_> {
    VoiceSurface(self)
  }
  /// The `Webapp` surface.
  pub fn webapp(&self) -> WebappSurface<'_> {
    WebappSurface(self)
  }
  /// The `Lyrics` surface.
  pub fn lyrics(&self) -> LyricsSurface<'_> {
    LyricsSurface(self)
  }
  /// The `Store` surface.
  pub fn store(&self) -> StoreSurface<'_> {
    StoreSurface(self)
  }
}

/// Methods scoped to the `Asset` wire surface.
pub struct AssetSurface<'a>(&'a Client);

impl<'a> AssetSurface<'a> {
  pub async fn preload(&self, payload: AssetPreload) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAssetMsgCommand::Preload(payload)).await
  }
  pub async fn get(&self, request: AssetGet) -> Result<AssetGot, RequestFailure<AssetNotFound>> {
    self.0.request(request).await
  }
  /// Stream of `Asset` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientAssetMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Asset(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Audio` wire surface.
pub struct AudioSurface<'a>(&'a Client);

impl<'a> AudioSurface<'a> {
  pub async fn volume_up(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::VolumeUp).await
  }
  pub async fn volume_down(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::VolumeDown).await
  }
  pub async fn set_volume(&self, payload: SetVolume) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::SetVolume(payload)).await
  }
  pub async fn mute_toggle(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::MuteToggle).await
  }
  pub async fn set_mute(&self, payload: SetMute) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::SetMute(payload)).await
  }
  pub async fn tts(&self, payload: Tts) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::Tts(payload)).await
  }
  pub async fn tts_cancel(&self, payload: TtsCancel) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::TtsCancel(payload)).await
  }
  pub async fn tts_cancel_all(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::TtsCancelAll).await
  }
  pub async fn earcon(&self, payload: Earcon) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeAudioMsgCommand::Earcon(payload)).await
  }
  /// Stream of `Audio` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientAudioMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Audio(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Bluetooth` wire surface.
pub struct BluetoothSurface<'a>(&'a Client);

impl<'a> BluetoothSurface<'a> {
  pub async fn connect(&self, payload: ConnectBluetooth) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeBluetoothMsgCommand::Connect(payload))
      .await
  }
  pub async fn enable_discoverable(&self) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeBluetoothMsgCommand::EnableDiscoverable)
      .await
  }
  pub async fn disable_discoverable(&self) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeBluetoothMsgCommand::DisableDiscoverable)
      .await
  }
  pub async fn forget(&self, payload: ForgetBluetooth) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeBluetoothMsgCommand::Forget(payload)).await
  }
  pub async fn set_alias(&self, payload: SetBluetoothAlias) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeBluetoothMsgCommand::SetAlias(payload))
      .await
  }
  pub async fn list(&self) -> Result<PairedDevicesMap, RequestFailure<::core::convert::Infallible>> {
    self.0.request(ListBluetoothDevices).await
  }
  /// Stream of `Bluetooth` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientBluetoothMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Bluetooth(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Capabilities` wire surface.
pub struct CapabilitiesSurface<'a>(&'a Client);

impl<'a> CapabilitiesSurface<'a> {
  pub async fn get(&self) -> Result<CapabilitiesSnapshot, RequestFailure<::core::convert::Infallible>> {
    self.0.request(CapabilitiesGet).await
  }
  /// Stream of `Capabilities` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientCapabilitiesMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Capabilities(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Config` wire surface.
pub struct ConfigSurface<'a>(&'a Client);

impl<'a> ConfigSurface<'a> {
  pub async fn get(&self, request: ConfigGet) -> Result<ConfigGetReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn list(&self) -> Result<ConfigListReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(ConfigList).await
  }
  /// Stream of `Config` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientConfigMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Config(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Doc` wire surface.
pub struct DocSurface<'a>(&'a Client);

impl<'a> DocSurface<'a> {
  pub async fn get(&self, request: DocGet) -> Result<DocGetReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn list(&self) -> Result<DocListReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(DocList).await
  }
  pub async fn set(&self, request: DocSet) -> Result<DocAck, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn delete(&self, request: DocDelete) -> Result<DocAck, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  /// Stream of `Doc` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientDocMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Doc(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Geo` wire surface.
pub struct GeoSurface<'a>(&'a Client);

impl<'a> GeoSurface<'a> {
  pub async fn unwatch(&self, payload: GeoUnwatch) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeGeoMsgCommand::Unwatch(payload)).await
  }
  pub async fn watch(&self, request: GeoWatch) -> Result<GeoWatchReply, RequestFailure<GeoErrorReply>> {
    self.0.request(request).await
  }
  pub async fn get_once(&self, request: GeoGetOnce) -> Result<GeoGetOnceReply, RequestFailure<GeoErrorReply>> {
    self.0.request(request).await
  }
  /// Stream of `Geo` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientGeoMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Geo(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Hardware` wire surface.
pub struct HardwareSurface<'a>(&'a Client);

impl<'a> HardwareSurface<'a> {
  pub async fn display_set_mode(&self, payload: DisplaySetMode) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeHardwareMsgCommand::DisplaySetMode(payload))
      .await
  }
  pub async fn display_set_level(&self, payload: DisplaySetLevel) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeHardwareMsgCommand::DisplaySetLevel(payload))
      .await
  }
  pub async fn display_set_rotation(&self, payload: DisplaySetRotation) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeHardwareMsgCommand::DisplaySetRotation(payload))
      .await
  }
  pub async fn state_get(&self) -> Result<HardwareStateReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(HardwareStateGet).await
  }
  /// Stream of `Hardware` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientHardwareMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Hardware(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Library` wire surface.
pub struct LibrarySurface<'a>(&'a Client);

impl<'a> LibrarySurface<'a> {
  pub async fn favorites_toggle(&self, payload: FavoritesToggle) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeLibraryMsgCommand::FavoritesToggle(payload))
      .await
  }
  pub async fn favorites_set(&self, payload: FavoritesSet) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeLibraryMsgCommand::FavoritesSet(payload))
      .await
  }
  pub async fn favorites_set_many(&self, payload: FavoritesSetMany) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeLibraryMsgCommand::FavoritesSetMany(payload))
      .await
  }
  pub async fn browse(&self, request: LibraryBrowse) -> Result<LibraryBrowseReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  pub async fn search(&self, request: LibrarySearch) -> Result<LibrarySearchReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  pub async fn recommendations(
    &self,
    request: LibraryRecommendations,
  ) -> Result<LibraryRecommendationsReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  pub async fn resolve_context(
    &self,
    request: LibraryResolveContext,
  ) -> Result<LibraryResolveContextReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  pub async fn favorites_list(
    &self,
    request: LibraryFavoritesList,
  ) -> Result<LibraryFavoritesListReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  pub async fn favorites_contains(
    &self,
    request: LibraryFavoritesContains,
  ) -> Result<LibraryFavoritesContainsReply, RequestFailure<LibraryErrorReply>> {
    self.0.request(request).await
  }
  /// Stream of `Library` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientLibraryMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Library(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Net` wire surface.
pub struct NetSurface<'a>(&'a Client);

impl<'a> NetSurface<'a> {
  pub async fn ws_close(&self, payload: NetWsClose) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeNetMsgCommand::WsClose(payload)).await
  }
  pub async fn ws_send(&self, payload: NetWsSend) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeNetMsgCommand::WsSend(payload)).await
  }
  pub async fn stream_open(&self, payload: NetStreamOpen) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeNetMsgCommand::StreamOpen(payload)).await
  }
  pub async fn stream_cancel(&self, payload: NetStreamCancel) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeNetMsgCommand::StreamCancel(payload)).await
  }
  pub async fn fetch(&self, request: NetFetch) -> Result<NetFetchReply, RequestFailure<NetFetchErrorReply>> {
    self.0.request(request).await
  }
  pub async fn ws_open(&self, request: NetWsOpen) -> Result<NetWsOpenReply, RequestFailure<NetWsErrorReply>> {
    self.0.request(request).await
  }
  /// Stream of `Net` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientNetMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Net(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Notifications` wire surface.
pub struct NotificationsSurface<'a>(&'a Client);

impl<'a> NotificationsSurface<'a> {
  pub async fn invoke_positive(&self, payload: NotificationInvoke) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeNotificationsMsgCommand::InvokePositive(payload))
      .await
  }
  pub async fn invoke_negative(&self, payload: NotificationInvoke) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeNotificationsMsgCommand::InvokeNegative(payload))
      .await
  }
  /// Stream of `Notifications` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientNotificationsMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Notifications(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Peer` wire surface.
pub struct PeerSurface<'a>(&'a Client);

impl<'a> PeerSurface<'a> {
  /// Stream of `Peer` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientPeerMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Peer(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Phone` wire surface.
pub struct PhoneSurface<'a>(&'a Client);

impl<'a> PhoneSurface<'a> {
  pub async fn answer(&self, payload: PhoneCallAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Answer(payload)).await
  }
  pub async fn accept(&self, payload: PhoneAcceptAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Accept(payload)).await
  }
  pub async fn decline(&self, payload: PhoneCallAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Decline(payload)).await
  }
  pub async fn end(&self, payload: PhoneCallAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::End(payload)).await
  }
  pub async fn end_typed(&self, payload: PhoneEndAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::EndTyped(payload)).await
  }
  pub async fn hold(&self, payload: PhoneCallAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Hold(payload)).await
  }
  pub async fn unhold(&self, payload: PhoneCallAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Unhold(payload)).await
  }
  pub async fn initiate(&self, payload: PhoneInitiateAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Initiate(payload)).await
  }
  pub async fn swap(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Swap).await
  }
  pub async fn merge(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Merge).await
  }
  pub async fn mute(&self, payload: PhoneMuteAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Mute(payload)).await
  }
  pub async fn dtmf(&self, payload: PhoneDtmfAction) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePhoneMsgCommand::Dtmf(payload)).await
  }
  pub async fn state_get(&self) -> Result<PhoneStateReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(PhoneStateGet).await
  }
  /// Stream of `Phone` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientPhoneMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Phone(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Player` wire surface.
pub struct PlayerSurface<'a>(&'a Client);

impl<'a> PlayerSurface<'a> {
  pub async fn play(&self, payload: PlayUri) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::Play(payload)).await
  }
  pub async fn queue(&self, payload: QueueUri) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::Queue(payload)).await
  }
  pub async fn pause(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::Pause).await
  }
  pub async fn resume(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::Resume).await
  }
  pub async fn skip_next(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::SkipNext).await
  }
  pub async fn skip_prev(&self, payload: SkipPrev) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::SkipPrev(payload)).await
  }
  pub async fn skip_to_index(&self, payload: SkipToIndex) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgePlayerMsgCommand::SkipToIndex(payload))
      .await
  }
  pub async fn seek_to(&self, payload: SeekTo) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::SeekTo(payload)).await
  }
  pub async fn set_shuffle(&self, payload: SetShuffle) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgePlayerMsgCommand::SetShuffle(payload))
      .await
  }
  pub async fn set_repeat(&self, payload: SetRepeat) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::SetRepeat(payload)).await
  }
  pub async fn set_speed(&self, payload: SetSpeed) -> Result<(), SdkError> {
    self.0.command(ClientToBridgePlayerMsgCommand::SetSpeed(payload)).await
  }
  pub async fn set_crossfade(&self, payload: SetCrossfade) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgePlayerMsgCommand::SetCrossfade(payload))
      .await
  }
  pub async fn transfer_to(&self, payload: TransferTo) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgePlayerMsgCommand::TransferTo(payload))
      .await
  }
  pub async fn state_get(&self) -> Result<PlayerStateReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(PlayerStateGet).await
  }
  pub async fn queue_get(&self) -> Result<PlayerQueueReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(PlayerQueueGet).await
  }
  pub async fn targets_get(&self) -> Result<PlayerTargetsReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(PlayerTargetsGet).await
  }
  /// Stream of `Player` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientPlayerMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Player(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `System` wire surface.
pub struct SystemSurface<'a>(&'a Client);

impl<'a> SystemSurface<'a> {
  pub async fn logs_unsubscribe(&self, payload: LogsUnsubscribe) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeSystemMsgCommand::LogsUnsubscribe(payload))
      .await
  }
  pub async fn reboot(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeSystemMsgCommand::Reboot).await
  }
  pub async fn power_off(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeSystemMsgCommand::PowerOff).await
  }
  pub async fn factory_reset(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeSystemMsgCommand::FactoryReset).await
  }
  pub async fn launcher_gesture_set(&self, payload: LauncherGestureSet) -> Result<(), SdkError> {
    self
      .0
      .command(ClientToBridgeSystemMsgCommand::LauncherGestureSet(payload))
      .await
  }
  pub async fn version_request(&self) -> Result<BridgeThingMeta, RequestFailure<::core::convert::Infallible>> {
    self.0.request(RequestVersion).await
  }
  pub async fn diagnostics_get(&self) -> Result<DiagnosticsReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(DiagnosticsGet).await
  }
  pub async fn logs_tail(
    &self,
    request: LogsTail,
  ) -> Result<LogsTailReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn logs_subscribe(
    &self,
    request: LogsSubscribe,
  ) -> Result<LogsSubscribeReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn device_get_nickname(&self) -> Result<DeviceNicknameReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(DeviceGetNickname).await
  }
  pub async fn launcher_gesture_get(
    &self,
  ) -> Result<LauncherGestureReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(LauncherGestureGet).await
  }
  /// Stream of `System` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientSystemMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::System(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Time` wire surface.
pub struct TimeSurface<'a>(&'a Client);

impl<'a> TimeSurface<'a> {
  pub async fn get(&self) -> Result<TimeSnapshot, RequestFailure<::core::convert::Infallible>> {
    self.0.request(TimeGet).await
  }
  /// Stream of `Time` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientTimeMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Time(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Voice` wire surface.
pub struct VoiceSurface<'a>(&'a Client);

impl<'a> VoiceSurface<'a> {
  pub async fn cancel(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeVoiceMsgCommand::Cancel).await
  }
  pub async fn push_to_talk(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeVoiceMsgCommand::PushToTalk).await
  }
  pub async fn release(&self) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeVoiceMsgCommand::Release).await
  }
  pub async fn mute_mic(&self, payload: MicMute) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeVoiceMsgCommand::MuteMic(payload)).await
  }
  pub async fn unmute_mic(&self, payload: MicUnmute) -> Result<(), SdkError> {
    self.0.command(ClientToBridgeVoiceMsgCommand::UnmuteMic(payload)).await
  }
  pub async fn state_get(&self) -> Result<VoiceStateReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(VoiceStateGet).await
  }
  /// Stream of `Voice` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientVoiceMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Voice(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Webapp` wire surface.
pub struct WebappSurface<'a>(&'a Client);

impl<'a> WebappSurface<'a> {
  pub async fn list(&self) -> Result<WebappListReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(WebappList).await
  }
  pub async fn current(&self) -> Result<WebappCurrentReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(WebappCurrent).await
  }
  pub async fn activate(&self, request: WebappActivate) -> Result<WebappActiveReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn icon(&self, request: WebappIcon) -> Result<WebappIconReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  /// Stream of `Webapp` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToClientWebappMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToClientMsgData::Webapp(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Lyrics` wire surface.
pub struct LyricsSurface<'a>(&'a Client);

impl<'a> LyricsSurface<'a> {
  pub async fn get(&self) -> Result<LyricsReply, RequestFailure<LyricsErrorReply>> {
    self.0.request(LyricsGet).await
  }
}

/// Methods scoped to the `Store` wire surface.
pub struct StoreSurface<'a>(&'a Client);

impl<'a> StoreSurface<'a> {
  pub async fn get(&self, request: KVGet) -> Result<StorageResponse, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn put(&self, request: KVPut) -> Result<StorageResponse, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn delete(
    &self,
    request: KVDelete,
  ) -> Result<StorageResponse, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
}
