// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.
// Re-generate with `just codegen` (or `just rust`).

use std::{future::Future, sync::Arc};

use crate::{Gateway, GatewayProtocol, HandlerError};
use bridgething_sdk_runtime::{Connection, Reply, RequestFailure, SdkError, rt};
use futures::{Stream, StreamExt, future::ready};
use libbridgething::wire::WireError;
use libbridgething::{gateway::*, *};
use tokio_stream::wrappers::BroadcastStream;
use uuid::Uuid;

impl Gateway {
  /// The `Audio` surface.
  pub fn audio(&self) -> AudioSurface<'_> {
    AudioSurface(self)
  }
  /// The `Geo` surface.
  pub fn geo(&self) -> GeoSurface<'_> {
    GeoSurface(self)
  }
  /// The `Library` surface.
  pub fn library(&self) -> LibrarySurface<'_> {
    LibrarySurface(self)
  }
  /// The `Net` surface.
  pub fn net(&self) -> NetSurface<'_> {
    NetSurface(self)
  }
  /// The `Notifications` surface.
  pub fn notifications(&self) -> NotificationsSurface<'_> {
    NotificationsSurface(self)
  }
  /// The `Phone` surface.
  pub fn phone(&self) -> PhoneSurface<'_> {
    PhoneSurface(self)
  }
  /// The `Player` surface.
  pub fn player(&self) -> PlayerSurface<'_> {
    PlayerSurface(self)
  }
  /// The `System` surface.
  pub fn system(&self) -> SystemSurface<'_> {
    SystemSurface(self)
  }
  /// The `Transfer` surface.
  pub fn transfer(&self) -> TransferSurface<'_> {
    TransferSurface(self)
  }
  /// The `Tunnel` surface.
  pub fn tunnel(&self) -> TunnelSurface<'_> {
    TunnelSurface(self)
  }
  /// The `Voice` surface.
  pub fn voice(&self) -> VoiceSurface<'_> {
    VoiceSurface(self)
  }
  /// The `Webapp` surface.
  pub fn webapp(&self) -> WebappSurface<'_> {
    WebappSurface(self)
  }
  /// The `Forward` surface.
  pub fn forward(&self) -> ForwardSurface<'_> {
    ForwardSurface(self)
  }
  /// The `Asset` surface.
  pub fn asset(&self) -> AssetSurface<'_> {
    AssetSurface(self)
  }
  /// The `Authority` surface.
  pub fn authority(&self) -> AuthoritySurface<'_> {
    AuthoritySurface(self)
  }
  /// The `Capabilities` surface.
  pub fn capabilities(&self) -> CapabilitiesSurface<'_> {
    CapabilitiesSurface(self)
  }
  /// The `Chrome` surface.
  pub fn chrome(&self) -> ChromeSurface<'_> {
    ChromeSurface(self)
  }
  /// The `Time` surface.
  pub fn time(&self) -> TimeSurface<'_> {
    TimeSurface(self)
  }
}

/// Methods scoped to the `Audio` wire surface.
pub struct AudioSurface<'a>(&'a Gateway);

impl<'a> AudioSurface<'a> {
  pub async fn tts_started(&self, payload: TtsStarted) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAudioMsgEvent::TtsStarted(payload)).await
  }
  pub async fn tts_ended(&self, payload: TtsEnded) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAudioMsgEvent::TtsEnded(payload)).await
  }
  pub async fn volume_changed(&self, payload: VolumeChanged) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAudioMsgEvent::VolumeChanged(payload)).await
  }
  pub async fn error_event(&self, payload: AudioErrorReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAudioMsgEvent::ErrorEvent(payload)).await
  }
}

/// Methods scoped to the `Geo` wire surface.
pub struct GeoSurface<'a>(&'a Gateway);

impl<'a> GeoSurface<'a> {
  pub async fn position(&self, payload: Position) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeGeoMsgEvent::Position(payload)).await
  }
  pub async fn error_event(&self, payload: GeoErrorReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeGeoMsgEvent::ErrorEvent(payload)).await
  }
}

/// Methods scoped to the `Library` wire surface.
pub struct LibrarySurface<'a>(&'a Gateway);

impl<'a> LibrarySurface<'a> {
  pub async fn favorite_changed(&self, payload: FavoriteChanged) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeLibraryMsgEvent::FavoriteChanged(payload))
      .await
  }
  pub async fn library_changed(&self, payload: LibraryChanged) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeLibraryMsgEvent::LibraryChanged(payload))
      .await
  }
  pub async fn error_event(&self, payload: LibraryErrorReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeLibraryMsgEvent::ErrorEvent(payload)).await
  }
}

/// Methods scoped to the `Net` wire surface.
pub struct NetSurface<'a>(&'a Gateway);

impl<'a> NetSurface<'a> {
  pub async fn ws_message(&self, payload: NetWsMessage) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::WsMessage(payload)).await
  }
  pub async fn ws_closed(&self, payload: NetWsClosed) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::WsClosed(payload)).await
  }
  pub async fn ws_error_event(&self, payload: NetWsErrorEvent) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::WsErrorEvent(payload)).await
  }
  pub async fn stream_begin(&self, payload: StreamBegin) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::StreamBegin(payload)).await
  }
  pub async fn stream_chunk(&self, payload: StreamChunk) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::StreamChunk(payload)).await
  }
  pub async fn stream_end(&self, payload: StreamEnd) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::StreamEnd(payload)).await
  }
  pub async fn stream_error(&self, payload: StreamError) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeNetMsgEvent::StreamError(payload)).await
  }
}

/// Methods scoped to the `Notifications` wire surface.
pub struct NotificationsSurface<'a>(&'a Gateway);

impl<'a> NotificationsSurface<'a> {
  pub async fn posted(&self, payload: Notification) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeNotificationsMsgEvent::Posted(payload))
      .await
  }
  pub async fn updated(&self, payload: Notification) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeNotificationsMsgEvent::Updated(payload))
      .await
  }
  pub async fn removed(&self, payload: NotificationRemoved) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeNotificationsMsgEvent::Removed(payload))
      .await
  }
  pub async fn error_event(&self, payload: NotificationsErrorReply) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeNotificationsMsgEvent::ErrorEvent(payload))
      .await
  }
  /// Stream of `Notifications` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewayNotificationsMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::Notifications(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Phone` wire surface.
pub struct PhoneSurface<'a>(&'a Gateway);

impl<'a> PhoneSurface<'a> {
  pub async fn snapshot(&self, payload: PhoneStateReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePhoneMsgEvent::Snapshot(payload)).await
  }
  pub async fn communications_snapshot(&self, payload: CommunicationsSnapshot) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgePhoneMsgEvent::CommunicationsSnapshot(payload))
      .await
  }
  pub async fn call_started(&self, payload: PhoneCall) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePhoneMsgEvent::CallStarted(payload)).await
  }
  pub async fn call_updated(&self, payload: PhoneCall) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePhoneMsgEvent::CallUpdated(payload)).await
  }
  pub async fn call_ended(&self, payload: PhoneCallEnded) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePhoneMsgEvent::CallEnded(payload)).await
  }
  pub async fn error_event(&self, payload: PhoneErrorReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePhoneMsgEvent::ErrorEvent(payload)).await
  }
}

/// Methods scoped to the `Player` wire surface.
pub struct PlayerSurface<'a>(&'a Gateway);

impl<'a> PlayerSurface<'a> {
  pub async fn snapshot(&self, payload: PlayerState) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgePlayerMsgEvent::Snapshot(Box::new(payload)))
      .await
  }
  pub async fn queue_changed(&self, payload: QueueSnapshot) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePlayerMsgEvent::QueueChanged(payload)).await
  }
  pub async fn targets_changed(&self, payload: PlaybackTargets) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgePlayerMsgEvent::TargetsChanged(payload))
      .await
  }
  pub async fn error_event(&self, payload: PlayerErrorReply) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgePlayerMsgEvent::ErrorEvent(payload)).await
  }
  pub async fn request_spotify_wake(&self, payload: SpotifyWakeRequest) -> Result<(), SdkError> {
    self
      .0
      .command(GatewayToBridgePlayerMsgCommand::RequestSpotifyWake(payload))
      .await
  }
}

/// Methods scoped to the `System` wire surface.
pub struct SystemSurface<'a>(&'a Gateway);

impl<'a> SystemSurface<'a> {
  pub async fn ota_abandon(&self, payload: OtaAbandon) -> Result<(), SdkError> {
    self
      .0
      .command(GatewayToBridgeSystemMsgCommand::OtaAbandon(payload))
      .await
  }
  pub async fn ota_activate(&self, payload: OtaActivate) -> Result<(), SdkError> {
    self
      .0
      .command(GatewayToBridgeSystemMsgCommand::OtaActivate(payload))
      .await
  }
  pub async fn cancel_update(&self) -> Result<(), SdkError> {
    self.0.command(GatewayToBridgeSystemMsgCommand::CancelUpdate).await
  }
  pub async fn launcher_gesture_set(&self, payload: LauncherGestureSet) -> Result<(), SdkError> {
    self
      .0
      .command(GatewayToBridgeSystemMsgCommand::LauncherGestureSet(payload))
      .await
  }
  pub async fn logs_unsubscribe(&self, payload: LogsUnsubscribe) -> Result<(), SdkError> {
    self
      .0
      .command(GatewayToBridgeSystemMsgCommand::LogsUnsubscribe(payload))
      .await
  }
  pub async fn ota_begin(&self, request: OtaBegin) -> Result<OtaBeginAck, RequestFailure<OtaBeginRejected>> {
    self.0.request(request).await
  }
  pub async fn device_get_nickname(&self) -> Result<DeviceNicknameReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(DeviceGetNickname).await
  }
  pub async fn device_set_nickname(
    &self,
    request: DeviceSetNickname,
  ) -> Result<DeviceNicknameReply, RequestFailure<DeviceNicknameRejected>> {
    self.0.request(request).await
  }
  pub async fn launcher_gesture_get(
    &self,
  ) -> Result<LauncherGestureReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(LauncherGestureGet).await
  }
  pub async fn logs_tail(
    &self,
    request: LogsTail,
  ) -> Result<LogsTailReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  pub async fn logs_subscribe(
    &self,
    request: LogsSubscribe,
  ) -> Result<LogsSubscribeReply, RequestFailure<::core::convert::Infallible>> {
    self.0.request(request).await
  }
  /// Stream of `System` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewaySystemMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::System(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Transfer` wire surface.
pub struct TransferSurface<'a>(&'a Gateway);

impl<'a> TransferSurface<'a> {
  pub async fn fragment(&self, payload: TransferFragment) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTransferMsgEvent::Fragment(payload)).await
  }
  pub async fn abandon(&self, payload: TransferAbandon) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTransferMsgEvent::Abandon(payload)).await
  }
  pub async fn ack(&self, payload: TransferAck) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTransferMsgEvent::Ack(payload)).await
  }
  /// Stream of `Transfer` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewayTransferMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::Transfer(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Tunnel` wire surface.
pub struct TunnelSurface<'a>(&'a Gateway);

impl<'a> TunnelSurface<'a> {
  pub async fn data(&self, payload: TunnelData) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTunnelMsgEvent::Data(payload)).await
  }
  pub async fn ack(&self, payload: TunnelAck) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTunnelMsgEvent::Ack(payload)).await
  }
  pub async fn closed(&self, payload: TunnelClosed) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTunnelMsgEvent::Closed(payload)).await
  }
}

/// Methods scoped to the `Voice` wire surface.
pub struct VoiceSurface<'a>(&'a Gateway);

impl<'a> VoiceSurface<'a> {
  pub async fn mic_open(&self, payload: VoiceMicOpen) -> Result<(), SdkError> {
    self.0.command(GatewayToBridgeVoiceMsgCommand::MicOpen(payload)).await
  }
  pub async fn mic_close(&self) -> Result<(), SdkError> {
    self.0.command(GatewayToBridgeVoiceMsgCommand::MicClose).await
  }
  pub async fn dispatch(&self, payload: VoiceDispatch) -> Result<(), SdkError> {
    self.0.command(GatewayToBridgeVoiceMsgCommand::Dispatch(payload)).await
  }
  /// Stream of `Voice` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewayVoiceMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::Voice(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Webapp` wire surface.
pub struct WebappSurface<'a>(&'a Gateway);

impl<'a> WebappSurface<'a> {
  pub async fn list(&self) -> Result<WebappList, RequestFailure<::core::convert::Infallible>> {
    self.0.request(ListWebapps).await
  }
  pub async fn get_active(&self) -> Result<WebappActive, RequestFailure<::core::convert::Infallible>> {
    self.0.request(GetActiveWebapp).await
  }
  pub async fn switch_to(&self, request: WebappSwitchTo) -> Result<WebappActive, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn uninstall(&self, request: WebappUninstall) -> Result<WebappActive, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn restore_builtin(
    &self,
    request: WebappRestoreBuiltin,
  ) -> Result<WebappActive, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn get_slots(&self) -> Result<WebappSlots, RequestFailure<::core::convert::Infallible>> {
    self.0.request(GetWebappSlots).await
  }
  pub async fn set_slot(&self, request: WebappSetSlot) -> Result<WebappSlots, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn resource(&self, request: WebappResource) -> Result<WebappResourceReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn config_get(
    &self,
    request: WebappConfigGet,
  ) -> Result<WebappConfigGetReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn config_list(
    &self,
    request: WebappConfigList,
  ) -> Result<WebappConfigListReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn config_set(&self, request: WebappConfigSet) -> Result<WebappConfigAck, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn config_delete(
    &self,
    request: WebappConfigDelete,
  ) -> Result<WebappConfigAck, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn doc_get(&self, request: WebappDocGet) -> Result<WebappDocGetReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn doc_list(&self, request: WebappDocList) -> Result<WebappDocListReply, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn doc_set(&self, request: WebappDocSet) -> Result<WebappDocAck, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  pub async fn doc_delete(&self, request: WebappDocDelete) -> Result<WebappDocAck, RequestFailure<WebappError>> {
    self.0.request(request).await
  }
  /// Stream of `Webapp` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewayWebappMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::Webapp(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Forward` wire surface.
pub struct ForwardSurface<'a>(&'a Gateway);

impl<'a> ForwardSurface<'a> {
  pub async fn routed(&self, payload: ForwardRouted) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeForwardMsgEvent::Routed(payload)).await
  }
  pub async fn extensions_running(&self, payload: ExtensionsRunning) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeForwardMsgEvent::ExtensionsRunning(payload))
      .await
  }
  /// Stream of `Forward` events.
  pub fn events(&self) -> impl Stream<Item = BridgeToGatewayForwardMsgEvent> + 'static {
    BroadcastStream::new(self.0.events()).filter_map(|msg| {
      ready(match msg {
        Ok(msg) => match msg.data {
          BridgeToGatewayMsgData::Forward(inner) => inner.into_event(),
          _ => None,
        },
        Err(_) => None,
      })
    })
  }
}

/// Methods scoped to the `Asset` wire surface.
pub struct AssetSurface<'a>(&'a Gateway);

impl<'a> AssetSurface<'a> {
  pub async fn clear(&self, payload: AssetClear) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAssetMsgEvent::Clear(payload)).await
  }
}

/// Methods scoped to the `Authority` wire surface.
pub struct AuthoritySurface<'a>(&'a Gateway);

impl<'a> AuthoritySurface<'a> {
  pub async fn claim(&self, payload: AuthorityClaim) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAuthorityMsgEvent::Claim(payload)).await
  }
  pub async fn release(&self, payload: AuthorityRelease) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeAuthorityMsgEvent::Release(payload)).await
  }
}

/// Methods scoped to the `Capabilities` wire surface.
pub struct CapabilitiesSurface<'a>(&'a Gateway);

impl<'a> CapabilitiesSurface<'a> {
  pub async fn announce(&self, payload: GatewayCapabilities) -> Result<(), SdkError> {
    self
      .0
      .event(GatewayToBridgeCapabilitiesMsgEvent::Announce(payload))
      .await
  }
}

/// Methods scoped to the `Chrome` wire surface.
pub struct ChromeSurface<'a>(&'a Gateway);

impl<'a> ChromeSurface<'a> {
  pub async fn navigate(&self, payload: ChromeNavigate) -> Result<(), SdkError> {
    self.0.command(GatewayToBridgeChromeMsgCommand::Navigate(payload)).await
  }
}

/// Methods scoped to the `Time` wire surface.
pub struct TimeSurface<'a>(&'a Gateway);

impl<'a> TimeSurface<'a> {
  pub async fn snapshot(&self, payload: TimeInfo) -> Result<(), SdkError> {
    self.0.event(GatewayToBridgeTimeMsgEvent::Snapshot(payload)).await
  }
}

pub trait AssetHandler {
  fn request(
    &self,
    request: AssetRequest,
  ) -> impl Future<Output = Result<Reply<AssetGotReply>, HandlerError<AssetNotFoundReply>>> + Send;
}

pub trait AudioHandler {
  fn volume_up(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn volume_down(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_volume(&self, payload: SetVolume) -> impl Future<Output = Result<(), WireError>> + Send;
  fn mute_toggle(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_mute(&self, payload: SetMute) -> impl Future<Output = Result<(), WireError>> + Send;
  fn tts(&self, payload: Tts) -> impl Future<Output = Result<(), WireError>> + Send;
  fn tts_cancel(&self, payload: TtsCancel) -> impl Future<Output = Result<(), WireError>> + Send;
  fn tts_cancel_all(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn earcon(&self, payload: Earcon) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait GeoHandler {
  fn get_once(
    &self,
    request: GeoGetOnce,
  ) -> impl Future<Output = Result<Reply<GeoGetOnceReply>, HandlerError<GeoErrorReply>>> + Send;
  fn watch(&self, payload: GeoWatch) -> impl Future<Output = Result<(), WireError>> + Send;
  fn unwatch(&self) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait LibraryHandler {
  fn browse(
    &self,
    request: LibraryBrowseRequest,
  ) -> impl Future<Output = Result<Reply<BrowseReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn resolve_context(
    &self,
    request: LibraryResolveContextRequest,
  ) -> impl Future<Output = Result<Reply<ContextResolveReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn search(
    &self,
    request: LibrarySearchRequest,
  ) -> impl Future<Output = Result<Reply<SearchReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn recommendations(
    &self,
    request: LibraryRecommendationsRequest,
  ) -> impl Future<Output = Result<Reply<RecommendationsReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn favorites_list(
    &self,
    request: LibraryFavoritesListRequest,
  ) -> impl Future<Output = Result<Reply<FavoritesListReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn favorites_contains(
    &self,
    request: LibraryFavoritesContainsRequest,
  ) -> impl Future<Output = Result<Reply<FavoritesContainsReply>, HandlerError<LibraryErrorReply>>> + Send;
  fn favorites_toggle(&self, payload: FavoritesToggle) -> impl Future<Output = Result<(), WireError>> + Send;
  fn favorites_set(&self, payload: FavoritesSet) -> impl Future<Output = Result<(), WireError>> + Send;
  fn favorites_set_many(&self, payload: FavoritesSetMany) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait LyricsHandler {
  fn get(
    &self,
    request: LyricsRequest,
  ) -> impl Future<Output = Result<Reply<LyricsReply>, HandlerError<LyricsErrorReply>>> + Send;
}

pub trait NetHandler {
  fn fetch(
    &self,
    request: NetFetchRequestMsg,
  ) -> impl Future<Output = Result<Reply<NetFetchReply>, HandlerError<NetFetchErrorReply>>> + Send;
  fn ws_open(
    &self,
    request: NetWsOpen,
  ) -> impl Future<Output = Result<Reply<NetWsOpenReply>, HandlerError<NetWsErrorReply>>> + Send;
  fn ws_close(&self, payload: NetWsClose) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ws_send(&self, payload: NetWsSend) -> impl Future<Output = Result<(), WireError>> + Send;
  fn stream_open(&self, payload: NetStreamOpen) -> impl Future<Output = Result<(), WireError>> + Send;
  fn stream_cancel(&self, payload: NetStreamCancel) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait NotificationsHandler {
  fn invoke_positive(&self, payload: NotificationInvoke) -> impl Future<Output = Result<(), WireError>> + Send;
  fn invoke_negative(&self, payload: NotificationInvoke) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ancs_auth_state_changed(&self, payload: AncsAuthState) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait PhoneHandler {
  fn state_get(
    &self,
  ) -> impl Future<Output = Result<Reply<PhoneStateReply>, HandlerError<::core::convert::Infallible>>> + Send;
  fn answer(&self, payload: PhoneCallAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn accept(&self, payload: PhoneAcceptAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn decline(&self, payload: PhoneCallAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn end(&self, payload: PhoneCallAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn end_typed(&self, payload: PhoneEndAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn hold(&self, payload: PhoneCallAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn unhold(&self, payload: PhoneCallAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn initiate(&self, payload: PhoneInitiateAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn swap(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn merge(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn mute(&self, payload: PhoneMuteAction) -> impl Future<Output = Result<(), WireError>> + Send;
  fn dtmf(&self, payload: PhoneDtmfAction) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait PlayerHandler {
  fn snapshot_request(
    &self,
    request: PlayerSnapshotRequest,
  ) -> impl Future<Output = Result<Reply<PlayerSnapshotAck>, HandlerError<PlayerErrorReply>>> + Send;
  fn play(&self, payload: PlayUri) -> impl Future<Output = Result<(), WireError>> + Send;
  fn queue(&self, payload: QueueUri) -> impl Future<Output = Result<(), WireError>> + Send;
  fn pause(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn resume(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn skip_next(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn skip_prev(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn skip_to_index(&self, payload: SkipToIndex) -> impl Future<Output = Result<(), WireError>> + Send;
  fn seek_to(&self, payload: SeekTo) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_shuffle(&self, payload: SetShuffle) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_repeat(&self, payload: SetRepeat) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_speed(&self, payload: SetSpeed) -> impl Future<Output = Result<(), WireError>> + Send;
  fn set_crossfade(&self, payload: SetCrossfade) -> impl Future<Output = Result<(), WireError>> + Send;
  fn transfer_to(&self, payload: TransferTo) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait SystemHandler {
  fn ota_asset_range(
    &self,
    id: Uuid,
    request: OtaAssetRange,
  ) -> impl Future<Output = Result<Reply<OtaAssetRangeReply>, HandlerError<OtaAssetRangeRejected>>> + Send;
  fn keepalive(
    &self,
    request: KeepalivePing,
  ) -> impl Future<Output = Result<Reply<KeepaliveAck>, HandlerError<::core::convert::Infallible>>> + Send;
  fn ota_progress(&self, payload: OtaProgress) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ota_error(&self, payload: OtaError) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ota_finished(&self, payload: OtaFinished) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ota_asset_range_abandon(
    &self,
    payload: OtaAssetRangeAbandon,
  ) -> impl Future<Output = Result<(), WireError>> + Send;
  fn device_nickname_changed(&self, payload: DeviceNicknameReply)
  -> impl Future<Output = Result<(), WireError>> + Send;
  fn launcher_gesture_changed(
    &self,
    payload: LauncherGestureReply,
  ) -> impl Future<Output = Result<(), WireError>> + Send;
  fn log_entry(&self, payload: LogEntry) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait TransferHandler {
  fn ack(&self, payload: TransferAck) -> impl Future<Output = Result<(), WireError>> + Send;
  fn fragment(&self, payload: TransferFragment) -> impl Future<Output = Result<(), WireError>> + Send;
  fn abandon(&self, payload: TransferAbandon) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait TunnelHandler {
  fn open(
    &self,
    request: TunnelOpen,
  ) -> impl Future<Output = Result<Reply<TunnelOpenReply>, HandlerError<TunnelErrorReply>>> + Send;
  fn data(&self, payload: TunnelData) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ack(&self, payload: TunnelAck) -> impl Future<Output = Result<(), WireError>> + Send;
  fn close(&self, payload: TunnelClosed) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait VoiceHandler {
  fn stream_open(&self, payload: VoiceStreamOpen) -> impl Future<Output = Result<(), WireError>> + Send;
  fn frame(&self, payload: VoiceFrame) -> impl Future<Output = Result<(), WireError>> + Send;
  fn stream_close(&self, payload: VoiceStreamClose) -> impl Future<Output = Result<(), WireError>> + Send;
  fn dispatched(&self, payload: VoiceDispatched) -> impl Future<Output = Result<(), WireError>> + Send;
  fn dispatch_failed(&self, payload: VoiceDispatchFailed) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait WebappHandler {
  fn doc_changed(&self, payload: WebappDocChanged) -> impl Future<Output = Result<(), WireError>> + Send;
  fn config_changed(&self, payload: WebappConfigChanged) -> impl Future<Output = Result<(), WireError>> + Send;
  fn webapp_installed(&self, payload: WebappInfo) -> impl Future<Output = Result<(), WireError>> + Send;
  fn active_changed(&self, payload: WebappActiveChanged) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait ForwardHandler {
  fn routed(&self, payload: ForwardRouted) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait EnvelopeHandler {
  fn version(&self, payload: BridgeThingMeta) -> impl Future<Output = Result<(), WireError>> + Send;
  fn error(&self, payload: WireError) -> impl Future<Output = Result<(), WireError>> + Send;
  fn ack(&self) -> impl Future<Output = Result<(), WireError>> + Send;
  fn done(&self) -> impl Future<Output = Result<(), WireError>> + Send;
}

pub trait GatewayHandlers:
  AssetHandler
  + AudioHandler
  + GeoHandler
  + LibraryHandler
  + LyricsHandler
  + NetHandler
  + NotificationsHandler
  + PhoneHandler
  + PlayerHandler
  + SystemHandler
  + TransferHandler
  + TunnelHandler
  + VoiceHandler
  + WebappHandler
  + ForwardHandler
  + EnvelopeHandler
  + Send
  + Sync
{
}

impl<T> GatewayHandlers for T where
  T: AssetHandler
    + AudioHandler
    + GeoHandler
    + LibraryHandler
    + LyricsHandler
    + NetHandler
    + NotificationsHandler
    + PhoneHandler
    + PlayerHandler
    + SystemHandler
    + TransferHandler
    + TunnelHandler
    + VoiceHandler
    + WebappHandler
    + ForwardHandler
    + EnvelopeHandler
    + Send
    + Sync
{
}

pub async fn route<H>(
  handlers: &Arc<H>,
  msg: BridgeToGatewayMsg,
  conn: &Connection<GatewayProtocol>,
) -> Result<(), SdkError>
where
  H: GatewayHandlers + 'static,
{
  let BridgeToGatewayMsg { id, data, .. } = msg;
  match data {
    BridgeToGatewayMsgData::Version(payload) => {
      if let Err(error) = <H as EnvelopeHandler>::version(handlers, *payload).await {
        tracing::warn!(surface = "envelope", variant = "version", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Asset(BridgeToGatewayAssetMsg::Request(request)) => {
      let handlers = handlers.clone();
      let conn = conn.clone();
      rt::spawn(async move {
        if let Err(error) = match <H as AssetHandler>::request(&handlers, request).await {
          Ok(reply) => {
            let sent = conn
              .respond_to_with::<AssetRequest>(
                id,
                reply.response,
                reply.priority.unwrap_or(Priority::Bulk),
                reply.compress,
              )
              .await;
            if let Some(after) = reply.after {
              after.await;
            }
            sent
          }
          Err(HandlerError::Domain(error)) => conn.respond_err::<AssetRequest>(id, error).await,
          Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
        } {
          tracing::warn!(
            surface = "asset",
            variant = "request",
            ?error,
            "the reply did not reach the peer"
          );
        }
      });
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::VolumeUp) => {
      if let Err(error) = <H as AudioHandler>::volume_up(handlers).await {
        tracing::warn!(surface = "audio", variant = "volumeUp", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::VolumeDown) => {
      if let Err(error) = <H as AudioHandler>::volume_down(handlers).await {
        tracing::warn!(surface = "audio", variant = "volumeDown", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::SetVolume(payload)) => {
      if let Err(error) = <H as AudioHandler>::set_volume(handlers, payload).await {
        tracing::warn!(surface = "audio", variant = "setVolume", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::MuteToggle) => {
      if let Err(error) = <H as AudioHandler>::mute_toggle(handlers).await {
        tracing::warn!(surface = "audio", variant = "muteToggle", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::SetMute(payload)) => {
      if let Err(error) = <H as AudioHandler>::set_mute(handlers, payload).await {
        tracing::warn!(surface = "audio", variant = "setMute", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::Tts(payload)) => {
      if let Err(error) = <H as AudioHandler>::tts(handlers, payload).await {
        tracing::warn!(surface = "audio", variant = "tts", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::TtsCancel(payload)) => {
      if let Err(error) = <H as AudioHandler>::tts_cancel(handlers, payload).await {
        tracing::warn!(surface = "audio", variant = "ttsCancel", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::TtsCancelAll) => {
      if let Err(error) = <H as AudioHandler>::tts_cancel_all(handlers).await {
        tracing::warn!(
          surface = "audio",
          variant = "ttsCancelAll",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Audio(BridgeToGatewayAudioMsg::Earcon(payload)) => {
      if let Err(error) = <H as AudioHandler>::earcon(handlers, payload).await {
        tracing::warn!(surface = "audio", variant = "earcon", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Geo(BridgeToGatewayGeoMsg::GetOnce(request)) => {
      match <H as GeoHandler>::get_once(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<GeoGetOnce>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<GeoGetOnce>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Geo(BridgeToGatewayGeoMsg::Watch(payload)) => {
      if let Err(error) = <H as GeoHandler>::watch(handlers, payload).await {
        tracing::warn!(surface = "geo", variant = "watch", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Geo(BridgeToGatewayGeoMsg::Unwatch) => {
      if let Err(error) = <H as GeoHandler>::unwatch(handlers).await {
        tracing::warn!(surface = "geo", variant = "unwatch", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::Browse(request)) => {
      match <H as LibraryHandler>::browse(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibraryBrowseRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibraryBrowseRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::ResolveContext(request)) => {
      match <H as LibraryHandler>::resolve_context(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibraryResolveContextRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibraryResolveContextRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::Search(request)) => {
      match <H as LibraryHandler>::search(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibrarySearchRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibrarySearchRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::Recommendations(request)) => {
      match <H as LibraryHandler>::recommendations(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibraryRecommendationsRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibraryRecommendationsRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::FavoritesList(request)) => {
      match <H as LibraryHandler>::favorites_list(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibraryFavoritesListRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibraryFavoritesListRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::FavoritesContains(request)) => {
      match <H as LibraryHandler>::favorites_contains(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LibraryFavoritesContainsRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LibraryFavoritesContainsRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::FavoritesToggle(payload)) => {
      if let Err(error) = <H as LibraryHandler>::favorites_toggle(handlers, payload).await {
        tracing::warn!(
          surface = "library",
          variant = "favoritesToggle",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::FavoritesSet(payload)) => {
      if let Err(error) = <H as LibraryHandler>::favorites_set(handlers, payload).await {
        tracing::warn!(
          surface = "library",
          variant = "favoritesSet",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Library(BridgeToGatewayLibraryMsg::FavoritesSetMany(payload)) => {
      if let Err(error) = <H as LibraryHandler>::favorites_set_many(handlers, payload).await {
        tracing::warn!(
          surface = "library",
          variant = "favoritesSetMany",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Lyrics(BridgeToGatewayLyricsMsg::Get(request)) => {
      match <H as LyricsHandler>::get(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<LyricsRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<LyricsRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::Fetch(request)) => {
      match <H as NetHandler>::fetch(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<NetFetchRequestMsg>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<NetFetchRequestMsg>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::WsOpen(request)) => {
      match <H as NetHandler>::ws_open(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<NetWsOpen>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<NetWsOpen>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::WsClose(payload)) => {
      if let Err(error) = <H as NetHandler>::ws_close(handlers, payload).await {
        tracing::warn!(surface = "net", variant = "wsClose", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::WsSend(payload)) => {
      if let Err(error) = <H as NetHandler>::ws_send(handlers, payload).await {
        tracing::warn!(surface = "net", variant = "wsSend", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::StreamOpen(payload)) => {
      if let Err(error) = <H as NetHandler>::stream_open(handlers, payload).await {
        tracing::warn!(surface = "net", variant = "streamOpen", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Net(BridgeToGatewayNetMsg::StreamCancel(payload)) => {
      if let Err(error) = <H as NetHandler>::stream_cancel(handlers, payload).await {
        tracing::warn!(surface = "net", variant = "streamCancel", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Notifications(BridgeToGatewayNotificationsMsg::InvokePositive(payload)) => {
      if let Err(error) = <H as NotificationsHandler>::invoke_positive(handlers, payload).await {
        tracing::warn!(
          surface = "notifications",
          variant = "invokePositive",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Notifications(BridgeToGatewayNotificationsMsg::InvokeNegative(payload)) => {
      if let Err(error) = <H as NotificationsHandler>::invoke_negative(handlers, payload).await {
        tracing::warn!(
          surface = "notifications",
          variant = "invokeNegative",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Notifications(BridgeToGatewayNotificationsMsg::AncsAuthStateChanged(payload)) => {
      if let Err(error) = <H as NotificationsHandler>::ancs_auth_state_changed(handlers, payload).await {
        tracing::warn!(
          surface = "notifications",
          variant = "ancsAuthStateChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::StateGet) => {
      match <H as PhoneHandler>::state_get(handlers).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<PhoneStateGet>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<PhoneStateGet>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Answer(payload)) => {
      if let Err(error) = <H as PhoneHandler>::answer(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "answer", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Accept(payload)) => {
      if let Err(error) = <H as PhoneHandler>::accept(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "accept", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Decline(payload)) => {
      if let Err(error) = <H as PhoneHandler>::decline(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "decline", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::End(payload)) => {
      if let Err(error) = <H as PhoneHandler>::end(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "end", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::EndTyped(payload)) => {
      if let Err(error) = <H as PhoneHandler>::end_typed(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "endTyped", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Hold(payload)) => {
      if let Err(error) = <H as PhoneHandler>::hold(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "hold", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Unhold(payload)) => {
      if let Err(error) = <H as PhoneHandler>::unhold(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "unhold", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Initiate(payload)) => {
      if let Err(error) = <H as PhoneHandler>::initiate(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "initiate", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Swap) => {
      if let Err(error) = <H as PhoneHandler>::swap(handlers).await {
        tracing::warn!(surface = "phone", variant = "swap", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Merge) => {
      if let Err(error) = <H as PhoneHandler>::merge(handlers).await {
        tracing::warn!(surface = "phone", variant = "merge", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Mute(payload)) => {
      if let Err(error) = <H as PhoneHandler>::mute(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "mute", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Phone(BridgeToGatewayPhoneMsg::Dtmf(payload)) => {
      if let Err(error) = <H as PhoneHandler>::dtmf(handlers, payload).await {
        tracing::warn!(surface = "phone", variant = "dtmf", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SnapshotRequest(request)) => {
      match <H as PlayerHandler>::snapshot_request(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<PlayerSnapshotRequest>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<PlayerSnapshotRequest>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::Play(payload)) => {
      if let Err(error) = <H as PlayerHandler>::play(handlers, payload).await {
        tracing::warn!(surface = "player", variant = "play", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::Queue(payload)) => {
      if let Err(error) = <H as PlayerHandler>::queue(handlers, payload).await {
        tracing::warn!(surface = "player", variant = "queue", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::Pause) => {
      if let Err(error) = <H as PlayerHandler>::pause(handlers).await {
        tracing::warn!(surface = "player", variant = "pause", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::Resume) => {
      if let Err(error) = <H as PlayerHandler>::resume(handlers).await {
        tracing::warn!(surface = "player", variant = "resume", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SkipNext) => {
      if let Err(error) = <H as PlayerHandler>::skip_next(handlers).await {
        tracing::warn!(surface = "player", variant = "skipNext", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SkipPrev) => {
      if let Err(error) = <H as PlayerHandler>::skip_prev(handlers).await {
        tracing::warn!(surface = "player", variant = "skipPrev", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SkipToIndex(payload)) => {
      if let Err(error) = <H as PlayerHandler>::skip_to_index(handlers, payload).await {
        tracing::warn!(
          surface = "player",
          variant = "skipToIndex",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SeekTo(payload)) => {
      if let Err(error) = <H as PlayerHandler>::seek_to(handlers, payload).await {
        tracing::warn!(surface = "player", variant = "seekTo", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SetShuffle(payload)) => {
      if let Err(error) = <H as PlayerHandler>::set_shuffle(handlers, payload).await {
        tracing::warn!(
          surface = "player",
          variant = "setShuffle",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SetRepeat(payload)) => {
      if let Err(error) = <H as PlayerHandler>::set_repeat(handlers, payload).await {
        tracing::warn!(surface = "player", variant = "setRepeat", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SetSpeed(payload)) => {
      if let Err(error) = <H as PlayerHandler>::set_speed(handlers, payload).await {
        tracing::warn!(surface = "player", variant = "setSpeed", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::SetCrossfade(payload)) => {
      if let Err(error) = <H as PlayerHandler>::set_crossfade(handlers, payload).await {
        tracing::warn!(
          surface = "player",
          variant = "setCrossfade",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Player(BridgeToGatewayPlayerMsg::TransferTo(payload)) => {
      if let Err(error) = <H as PlayerHandler>::transfer_to(handlers, payload).await {
        tracing::warn!(
          surface = "player",
          variant = "transferTo",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaAssetRange(request)) => {
      let handlers = handlers.clone();
      let conn = conn.clone();
      rt::spawn(async move {
        if let Err(error) = match <H as SystemHandler>::ota_asset_range(&handlers, id, request).await {
          Ok(reply) => {
            let sent = conn
              .respond_to_with::<OtaAssetRange>(
                id,
                reply.response,
                reply.priority.unwrap_or(Priority::Normal),
                reply.compress,
              )
              .await;
            if let Some(after) = reply.after {
              after.await;
            }
            sent
          }
          Err(HandlerError::Domain(error)) => conn.respond_err::<OtaAssetRange>(id, error).await,
          Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
        } {
          tracing::warn!(
            surface = "system",
            variant = "otaAssetRange",
            ?error,
            "the reply did not reach the peer"
          );
        }
      });
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::Keepalive(request)) => {
      match <H as SystemHandler>::keepalive(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<KeepalivePing>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<KeepalivePing>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaProgress(payload)) => {
      if let Err(error) = <H as SystemHandler>::ota_progress(handlers, payload).await {
        tracing::warn!(
          surface = "system",
          variant = "otaProgress",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaError(payload)) => {
      if let Err(error) = <H as SystemHandler>::ota_error(handlers, payload).await {
        tracing::warn!(surface = "system", variant = "otaError", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaFinished(payload)) => {
      if let Err(error) = <H as SystemHandler>::ota_finished(handlers, payload).await {
        tracing::warn!(
          surface = "system",
          variant = "otaFinished",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaBeginAck(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "otaBeginAck",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaBeginRejected(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "otaBeginRejected",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::OtaAssetRangeAbandon(payload)) => {
      if let Err(error) = <H as SystemHandler>::ota_asset_range_abandon(handlers, payload).await {
        tracing::warn!(
          surface = "system",
          variant = "otaAssetRangeAbandon",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::DeviceNickname(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "deviceNickname",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::DeviceNicknameRejected(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "deviceNicknameRejected",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::DeviceNicknameChanged(payload)) => {
      if let Err(error) = <H as SystemHandler>::device_nickname_changed(handlers, payload).await {
        tracing::warn!(
          surface = "system",
          variant = "deviceNicknameChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::LauncherGestureReply(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "launcherGestureReply",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::LauncherGestureChanged(payload)) => {
      if let Err(error) = <H as SystemHandler>::launcher_gesture_changed(handlers, payload).await {
        tracing::warn!(
          surface = "system",
          variant = "launcherGestureChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::LogsTailReply(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "logsTailReply",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::LogsSubscribeReply(_)) => {
      tracing::debug!(
        surface = "system",
        variant = "logsSubscribeReply",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::System(BridgeToGatewaySystemMsg::LogEntry(payload)) => {
      if let Err(error) = <H as SystemHandler>::log_entry(handlers, payload).await {
        tracing::warn!(surface = "system", variant = "logEntry", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Transfer(BridgeToGatewayTransferMsg::Ack(payload)) => {
      if let Err(error) = <H as TransferHandler>::ack(handlers, payload).await {
        tracing::warn!(surface = "transfer", variant = "ack", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Transfer(BridgeToGatewayTransferMsg::Fragment(payload)) => {
      if let Err(error) = <H as TransferHandler>::fragment(handlers, payload).await {
        tracing::warn!(
          surface = "transfer",
          variant = "fragment",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Transfer(BridgeToGatewayTransferMsg::Abandon(payload)) => {
      if let Err(error) = <H as TransferHandler>::abandon(handlers, payload).await {
        tracing::warn!(surface = "transfer", variant = "abandon", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Tunnel(BridgeToGatewayTunnelMsg::Open(request)) => {
      match <H as TunnelHandler>::open(handlers, request).await {
        Ok(reply) => {
          let sent = conn
            .respond_to_with::<TunnelOpen>(
              id,
              reply.response,
              reply.priority.unwrap_or(Priority::Normal),
              reply.compress,
            )
            .await;
          if let Some(after) = reply.after {
            after.await;
          }
          sent
        }
        Err(HandlerError::Domain(error)) => conn.respond_err::<TunnelOpen>(id, error).await,
        Err(HandlerError::Wire(error)) => conn.respond(id, error.into()).await,
      }
    }
    BridgeToGatewayMsgData::Tunnel(BridgeToGatewayTunnelMsg::Data(payload)) => {
      if let Err(error) = <H as TunnelHandler>::data(handlers, payload).await {
        tracing::warn!(surface = "tunnel", variant = "data", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Tunnel(BridgeToGatewayTunnelMsg::Ack(payload)) => {
      if let Err(error) = <H as TunnelHandler>::ack(handlers, payload).await {
        tracing::warn!(surface = "tunnel", variant = "ack", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Tunnel(BridgeToGatewayTunnelMsg::Close(payload)) => {
      if let Err(error) = <H as TunnelHandler>::close(handlers, payload).await {
        tracing::warn!(surface = "tunnel", variant = "close", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Voice(BridgeToGatewayVoiceMsg::StreamOpen(payload)) => {
      if let Err(error) = <H as VoiceHandler>::stream_open(handlers, payload).await {
        tracing::warn!(surface = "voice", variant = "streamOpen", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Voice(BridgeToGatewayVoiceMsg::Frame(payload)) => {
      if let Err(error) = <H as VoiceHandler>::frame(handlers, payload).await {
        tracing::warn!(surface = "voice", variant = "frame", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Voice(BridgeToGatewayVoiceMsg::StreamClose(payload)) => {
      if let Err(error) = <H as VoiceHandler>::stream_close(handlers, payload).await {
        tracing::warn!(
          surface = "voice",
          variant = "streamClose",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Voice(BridgeToGatewayVoiceMsg::Dispatched(payload)) => {
      if let Err(error) = <H as VoiceHandler>::dispatched(handlers, payload).await {
        tracing::warn!(surface = "voice", variant = "dispatched", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Voice(BridgeToGatewayVoiceMsg::DispatchFailed(payload)) => {
      if let Err(error) = <H as VoiceHandler>::dispatch_failed(handlers, payload).await {
        tracing::warn!(
          surface = "voice",
          variant = "dispatchFailed",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Webapps(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "webapps",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Active(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "active",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Switched(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "switched",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Uninstalled(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "uninstalled",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Restored(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "restored",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::WebappError(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "webappError",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Resource(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "resource",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::Slots(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "slots",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::ConfigGet(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "configGet",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::ConfigList(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "configList",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::ConfigAck(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "configAck",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::DocGet(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "docGet",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::DocList(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "docList",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::DocAck(_)) => {
      tracing::debug!(
        surface = "webapp",
        variant = "docAck",
        "response with no pending request"
      );
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::DocChanged(payload)) => {
      if let Err(error) = <H as WebappHandler>::doc_changed(handlers, payload).await {
        tracing::warn!(
          surface = "webapp",
          variant = "docChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::ConfigChanged(payload)) => {
      if let Err(error) = <H as WebappHandler>::config_changed(handlers, payload).await {
        tracing::warn!(
          surface = "webapp",
          variant = "configChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::WebappInstalled(payload)) => {
      if let Err(error) = <H as WebappHandler>::webapp_installed(handlers, payload).await {
        tracing::warn!(
          surface = "webapp",
          variant = "webappInstalled",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Webapp(BridgeToGatewayWebappMsg::ActiveChanged(payload)) => {
      if let Err(error) = <H as WebappHandler>::active_changed(handlers, payload).await {
        tracing::warn!(
          surface = "webapp",
          variant = "activeChanged",
          ?error,
          "inbound not handled"
        );
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Forward(BridgeToGatewayForwardMsg::Routed(payload)) => {
      if let Err(error) = <H as ForwardHandler>::routed(handlers, payload).await {
        tracing::warn!(surface = "forward", variant = "routed", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Error(payload) => {
      if let Err(error) = <H as EnvelopeHandler>::error(handlers, payload).await {
        tracing::warn!(surface = "envelope", variant = "error", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Ack => {
      if let Err(error) = <H as EnvelopeHandler>::ack(handlers).await {
        tracing::warn!(surface = "envelope", variant = "ack", ?error, "inbound not handled");
      }
      Ok(())
    }
    BridgeToGatewayMsgData::Done => {
      if let Err(error) = <H as EnvelopeHandler>::done(handlers).await {
        tracing::warn!(surface = "envelope", variant = "done", ?error, "inbound not handled");
      }
      Ok(())
    }
  }
}
